# -*- coding: utf-8 -*-
"""Health Care Data -Week-06

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dIyPvDGLsTiW8np8dwlUx9uA1vSuvRv0
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_csv("/content/healthcare_dataset.csv")

df

print(df.head())

billing_data = df.groupby(
    ['Medical Condition', 'Insurance Provider']
)['Billing Amount'].sum().unstack(fill_value=0)

billing_data.plot(
    kind='bar',
    stacked=True,
    figsize=(12, 6)
)

import seaborn as sns

plt.figure(figsize=(12, 6))

sns.violinplot(
    data=df,
    x='Medical Condition',
    y='Billing Amount'
)

plt.title('Billing Amount by Medical Condition and Insurance Provider')
plt.xlabel('Medical Condition')
plt.ylabel('Total Billing Amount')
plt.xticks(rotation=45)
plt.legend(title='Insurance Provider')
plt.tight_layout()
plt.show()

plt.title('Billing Amount Distribution by Medical Condition')
plt.xlabel('Medical Condition')
plt.ylabel('Billing Amount')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

plt.figure(figsize=(12, 6))

sns.violinplot(
    data=df,
    x='Insurance Provider',
    y='Billing Amount'
)

plt.title('Billing Amount Distribution by Insurance Provider')
plt.xlabel('Insurance Provider')
plt.ylabel('Billing Amount')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()