# -*- coding: utf-8 -*-
"""Shopify Stock Data -DV -Week-04

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oJlv3MTrS3cRCsgoNZx_uwO5xS6W6x-C
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_csv("/content/shopify_stock.csv")
print(df.head())

plt.plot(df["date"], df["close"])

plt.xlabel("Date")
plt.ylabel("Closing Price")
plt.title("Shopify Stock Price")

plt.show()